### ISSUE TITLE
RGBW Output

### ISSUE THREAD

**Issue by hputzek** [martinberlin/udpx#4] opened 2019-09-06 16:17 UTC
Hi @martinberlin 

The RGBW Output did not work on the Pixels+s Branch.

* I had to comment out some #if statements
* the neopixelbus stripe type for rgbw was wrong (error was no function .... found in class ...)

* In frontend when I selected the W - Channel only (so rgbw(0,0,0,255) the stripe did not show white but a mix of colors... 

I rudimentarily fixed the firmware to use rgbw, shall I push that to a separate Branch?

@IoTPanic has added the mechanics with those #if statements to enable rgbw, maybe he knows why it did not work this way?
I didnt just push my stuff because I dont want to mess with your code.

You have the 144px stripe I send you, are you willing to test with this and update the branch accordingly?

**Comment by martinberlin** [comment] 2019-09-06 18:24
Sure I will test over the weekend with this and make sure it outputs the color. However I cannot reproduce the >288 at least I can try to simulate it. 
I sent up to 900px to my RGB and it does work.

**Comment by martinberlin** [comment] 2019-09-07 06:03
Fixed and merged in develop.
Thanks for your support Samuel. Let's please stick to the branching model explained here:
https://github.com/martinberlin/udpx/tree/develop#branching-model

**Closed as completed by martinberlin** 2019-09-07 06:03 UTC
Labels: bug
